### ISSUE TITLE
Process?

### ISSUE THREAD

**Issue by dol0han** [DeadTheAmazing/TestFuck-Interpreter#1]
Hello, thanks for the awesome program here. Do you have any other readme/doc??? I don't really understand 100%. Seems very interesting and i would like to try it out. So, could you improve the current docs or is that out of the question? thanks.

**Comment by DeadTheAmazing** [comment]
Hello, thank you for your feed back! I will simplify the docs for you!

**Comment by DeadTheAmazing** [comment]
Please let me know how the doc works out for you. This program is almost a year old so the website could have been updated. I will not be reworking the code if this becomes an issue.

Reply to this issue with your results!

**Comment by 4yz** [comment]
It does not seem to be working anymore. I keep getting empty arrays - I'm thinking by the time the question loads, it is too late since the program retrieves the elements within the question too soon.

**Comment by gscoutis** [comment]
doesn't work anymore

**Comment by DeadTheAmazing** [comment]
yes I'm aware, I do not plan on working on this again. sorry!
